var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/terms/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nlo7sz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-hdv5-.js")
R.c("server/chunks/ssr/[root-of-the-server]__00r512t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_app_(dashboard)_layout_tsx_0viz0w8._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(dashboard)_terms_page_actions_0u6fw1j.js")
R.m(21333)
module.exports=R.m(21333).exports
