var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/report-card-design/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p~_._a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0lh8~5j.js")
R.c("server/chunks/ssr/[root-of-the-server]__00r512t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_app_(dashboard)_layout_tsx_0viz0w8._.js")
R.c("server/chunks/ssr/09og__next-internal_server_app_(dashboard)_report-card-design_page_actions_09cdf6h.js")
R.m(15831)
module.exports=R.m(15831).exports
