var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0671wwq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ev7v39.js")
R.c("server/chunks/ssr/[root-of-the-server]__00r512t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_privacy_page_actions_0f7r7wp.js")
R.m(70105)
module.exports=R.m(70105).exports
