var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/subjects/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cqu18h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0k4c9a2.js")
R.c("server/chunks/ssr/[root-of-the-server]__00r512t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_app_(dashboard)_layout_tsx_0viz0w8._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(dashboard)_subjects_page_actions_0l_e03z.js")
R.m(11524)
module.exports=R.m(11524).exports
