var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jnlzli._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y-legz.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zsopez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(auth)_register_page_actions_0ts1lo..js")
R.m(52149)
module.exports=R.m(52149).exports
