var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/teachers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04q95dh._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0t-lfcn.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zsopez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_app_(dashboard)_layout_tsx_0viz0w8._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(dashboard)_teachers_page_actions_0zflq_e.js")
R.m(57679)
module.exports=R.m(57679).exports
