// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/academic-year" | "/class-list-design" | "/class-master" | "/classes" | "/courses" | "/dashboard" | "/fees" | "/grading-scale" | "/hnd-registration" | "/login" | "/print/class/[classLevel]" | "/privacy" | "/register" | "/report-card-design" | "/report-cards" | "/report-cards/[id]" | "/report-cards/class/[classLevel]" | "/report-cards/class/[classLevel]/[subjectId]" | "/report-cards/transcript/[studentId]" | "/settings" | "/students" | "/subjects" | "/superadmin" | "/superadmin/schools/[id]" | "/teachers" | "/terms"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/academic-year": {}
  "/class-list-design": {}
  "/class-master": {}
  "/classes": {}
  "/courses": {}
  "/dashboard": {}
  "/fees": {}
  "/grading-scale": {}
  "/hnd-registration": {}
  "/login": {}
  "/print/class/[classLevel]": { "classLevel": string; }
  "/privacy": {}
  "/register": {}
  "/report-card-design": {}
  "/report-cards": {}
  "/report-cards/[id]": { "id": string; }
  "/report-cards/class/[classLevel]": { "classLevel": string; }
  "/report-cards/class/[classLevel]/[subjectId]": { "classLevel": string; "subjectId": string; }
  "/report-cards/transcript/[studentId]": { "studentId": string; }
  "/settings": {}
  "/students": {}
  "/subjects": {}
  "/superadmin": {}
  "/superadmin/schools/[id]": { "id": string; }
  "/teachers": {}
  "/terms": {}
  "/uploads/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
