// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/academic-year/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academic-year">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/academic-year/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/class-list-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/class-list-design">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/class-list-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/class-master/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/class-master">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/class-master/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fees">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/grading-scale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grading-scale">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/grading-scale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hnd-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hnd-registration">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hnd-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-card-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-card-design">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-card-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-cards/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-cards/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-cards/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-cards/class/[classLevel]/[subjectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-cards/class/[classLevel]/[subjectId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-cards/class/[classLevel]/[subjectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-cards/class/[classLevel]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-cards/class/[classLevel]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-cards/class/[classLevel]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-cards">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/report-cards/transcript/[studentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-cards/transcript/[studentId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/report-cards/transcript/[studentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/students">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/subjects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subjects">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/subjects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/superadmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/superadmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/superadmin/schools/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/schools/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/superadmin/schools/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teachers">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(print)/print/class/[classLevel]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/class/[classLevel]">> = Specific
  const handler = {} as typeof import("../../app/(print)/print/class/[classLevel]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
