var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/superadmin/schools/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~ec4-d._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0awapn7.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zsopez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v4seaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_app_(dashboard)_layout_tsx_0viz0w8._.js")
R.c("server/chunks/ssr/0z2a_server_app_(dashboard)_superadmin_schools_[id]_page_actions_0rv-t~1.js")
R.m(70978)
module.exports=R.m(70978).exports
